package com.fijib.impl.persistence.entity;

// Generated Aug 21, 2014 11:10:22 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Agence generated by hbm2java
 */
@Entity
@Table(name = "agence", catalog = "db_fijib")
public class Agence implements java.io.Serializable {

	private Integer agenceId;
	private String adresseAgence;
	private String agenceName;
	private String tel;
	private Set<Agentguichet> agentguichets = new HashSet<Agentguichet>(0);

	public Agence() {
	}

	public Agence(String adresseAgence, String agenceName, String tel,
			Set<Agentguichet> agentguichets) {
		this.adresseAgence = adresseAgence;
		this.agenceName = agenceName;
		this.tel = tel;
		this.agentguichets = agentguichets;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "AgenceId", unique = true, nullable = false)
	public Integer getAgenceId() {
		return this.agenceId;
	}

	public void setAgenceId(Integer agenceId) {
		this.agenceId = agenceId;
	}

	@Column(name = "AdresseAgence", length = 254)
	public String getAdresseAgence() {
		return this.adresseAgence;
	}

	public void setAdresseAgence(String adresseAgence) {
		this.adresseAgence = adresseAgence;
	}

	@Column(name = "AgenceName", length = 254)
	public String getAgenceName() {
		return this.agenceName;
	}

	public void setAgenceName(String agenceName) {
		this.agenceName = agenceName;
	}

	@Column(name = "Tel", length = 254)
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "agence")
	public Set<Agentguichet> getAgentguichets() {
		return this.agentguichets;
	}

	public void setAgentguichets(Set<Agentguichet> agentguichets) {
		this.agentguichets = agentguichets;
	}

}
