package com.fijib.impl.persistence.entity;

// Generated Aug 21, 2014 11:10:22 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Faq generated by hbm2java
 */
@Entity
@Table(name = "faq", catalog = "db_fijib")
public class Faq implements java.io.Serializable {

	private Integer idFaq;
	private String question;
	private String reponse;

	public Faq() {
	}

	public Faq(String question, String reponse) {
		this.question = question;
		this.reponse = reponse;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idFAQ", unique = true, nullable = false)
	public Integer getIdFaq() {
		return this.idFaq;
	}

	public void setIdFaq(Integer idFaq) {
		this.idFaq = idFaq;
	}

	@Column(name = "Question", length = 254)
	public String getQuestion() {
		return this.question;
	}

	public void setQuestion(String question) {
		this.question = question;
	}

	@Column(name = "reponse", length = 254)
	public String getReponse() {
		return this.reponse;
	}

	public void setReponse(String reponse) {
		this.reponse = reponse;
	}

}
