package com.fijib.impl.persistence.entity;

// Generated Aug 21, 2014 11:10:22 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Listeprefere generated by hbm2java
 */
@Entity
@Table(name = "listeprefere", catalog = "db_fijib")
public class Listeprefere implements java.io.Serializable {

	private Integer idListe;
	private Client clientByCinBene;
	private Client clientByCliCinEnv;

	public Listeprefere() {
	}

	public Listeprefere(Client clientByCinBene, Client clientByCliCinEnv) {
		this.clientByCinBene = clientByCinBene;
		this.clientByCliCinEnv = clientByCliCinEnv;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_Liste", unique = true, nullable = false)
	public Integer getIdListe() {
		return this.idListe;
	}

	public void setIdListe(Integer idListe) {
		this.idListe = idListe;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CIN_BENE" )
	public Client getClientByCinBene() {
		return this.clientByCinBene;
	}

	public void setClientByCinBene(Client clientByCinBene) {
		this.clientByCinBene = clientByCinBene;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Cli_CIN_ENV" )
	public Client getClientByCliCinEnv() {
		return this.clientByCliCinEnv;
	}

	public void setClientByCliCinEnv(Client clientByCliCinEnv) {
		this.clientByCliCinEnv = clientByCliCinEnv;
	}

}
