package com.fijib.impl.persistence.entity;

// Generated Aug 21, 2014 11:10:22 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Statistiquegenerale generated by hbm2java
 */
@Entity
@Table(name = "statistiquegenerale", catalog = "db_fijib")
public class Statistiquegenerale implements java.io.Serializable {

	private Integer idStatistique;
	private Integer montantTotalTransfere;
	private Integer nbrClientTotal;
	private Integer nbrClientTrans;
	private Integer nbrTransTotal;

	public Statistiquegenerale() {
	}

	public Statistiquegenerale(Integer montantTotalTransfere,
			Integer nbrClientTotal, Integer nbrClientTrans,
			Integer nbrTransTotal) {
		this.montantTotalTransfere = montantTotalTransfere;
		this.nbrClientTotal = nbrClientTotal;
		this.nbrClientTrans = nbrClientTrans;
		this.nbrTransTotal = nbrTransTotal;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_Statistique", unique = true, nullable = false)
	public Integer getIdStatistique() {
		return this.idStatistique;
	}

	public void setIdStatistique(Integer idStatistique) {
		this.idStatistique = idStatistique;
	}

	@Column(name = "montantTotalTransfere")
	public Integer getMontantTotalTransfere() {
		return this.montantTotalTransfere;
	}

	public void setMontantTotalTransfere(Integer montantTotalTransfere) {
		this.montantTotalTransfere = montantTotalTransfere;
	}

	@Column(name = "nbrClientTotal")
	public Integer getNbrClientTotal() {
		return this.nbrClientTotal;
	}

	public void setNbrClientTotal(Integer nbrClientTotal) {
		this.nbrClientTotal = nbrClientTotal;
	}

	@Column(name = "nbrClientTrans")
	public Integer getNbrClientTrans() {
		return this.nbrClientTrans;
	}

	public void setNbrClientTrans(Integer nbrClientTrans) {
		this.nbrClientTrans = nbrClientTrans;
	}

	@Column(name = "nbrTransTotal")
	public Integer getNbrTransTotal() {
		return this.nbrTransTotal;
	}

	public void setNbrTransTotal(Integer nbrTransTotal) {
		this.nbrTransTotal = nbrTransTotal;
	}

}
